### ISSUE TITLE
Importing on Windows 10 requires Bypass ExecutionPolicy

### ISSUE THREAD

**Issue by chefsas** [tydeno/Ploto#25]
1. THIS THING IS AWESOME!!!
2. How can I support your work?

On to the real issue -- I followed your readme and set my executionpolicy to RemoteSigned and it didn't work. I got a message that said the file is not digitally signed. So I had to set the policy to bypass to get it to import. I've attached three screenshots:

Screen1 = Where I set the execution policy to RemoteSigned as you specified
Screen2 = Verified it was set correctly
Screen3 = Set execution policy to Bypass and it imported and is working great now

![Screen1](https://user-images.githubusercontent.com/74569709/117892730-dd19a180-b27e-11eb-82db-205e15002c5a.jpg)
![Screen2](https://user-images.githubusercontent.com/74569709/117892732-dee36500-b27e-11eb-9187-77c4f4af4a8c.jpg)
![Screen3](https://user-images.githubusercontent.com/74569709/117892736-e0ad2880-b27e-11eb-8b03-00c66c7df127.jpg)

**Comment by tydeno** [comment]
Hei @chefsas. Thank you for your feedback. Glad you like it :) 
What I see from screenshot 1, is that the path specified to Ploto Module seems invalid. Thats what the error says. So I think, Import-Module would potentially also have worked without setting ExecutionPolicy to "Bypass". However, I'll add that to the readme. 

Regarding the question how you can support my work. There are quite a few things :)
- Use it and provide feedback about what works and what now
- Spread the word, so that more people use and test it (What you're already doing it seems)
- If you can and want to you're of course also invited to contribute your pieces of PowerShell to the module by submitting pull requests
- And just to round it up; If you like, you may also support me trough donations. Preferrably in XCH, as I'm still sitting at 0 🌱 :P
   - XCH Adress: I dont know right now, need to check wallet address when I'm home.
   - BTC Adress: 1HAhnWKABayn5tHi5dyDAQVLJtavtXpGHM
   - ETH Adress: 0x0098d6cab9c10ae8648340c0b9d86beb417194a5

**Comment by chefsas** [comment]
I took the wrong screenshot -- I promise I had the path right. I'll do it again and get you the right screenshot. Should I open this bug again?

**Comment by chefsas** [comment]
Here's the screenshot I was talking about. As you can see it will not work under RemoteSigned.

![Screen4](https://user-images.githubusercontent.com/74569709/118066168-d749bc00-b363-11eb-8d37-37ddbc810b68.jpg)

**Comment by tydeno** [comment]
Alright I see that now :P WIll add it to the docs. Tyvm!

**Comment by tydeno** [comment]
Has been added to doc.
